// <auto-generated />
using System;
using FanoutMessageProducer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FanoutMessageProducer.Migrations
{
    [DbContext(typeof(ProducerDbContext))]
    [Migration("20210824110919_Initial_ProducerDetails_Producer")]
    partial class Initial_ProducerDetails_Producer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("FanoutMessageLibrary.Models.ProducerDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ProducerMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProducerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("ProducerDetails_Table");
                });
#pragma warning restore 612, 618
        }
    }
}
